blog/urls.py
from django.urls import path
from .feeds import LatestPostFeeds
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.home, name="home"),
    path('tag/<slug:tag_slug>/', views.home, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail_view, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostFeeds(), name="post_feed"),
    path("search", views.post_search, name="post_search"),
]

eBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts':PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls", namespace='blog')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User  
from django.urls import reverse
from taggit.managers import TaggableManager


class PublisedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .filter(status=Post.Status.PUBLISHED)


class DraftManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .filter(status=Post.Status.DRAFT)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'DRAFT'
        PUBLISHED = 'PB', 'Published'

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')  
    body = models.TextField()
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    published = PublisedManager() 
    drafted = DraftManager()
    tags = TaggableManager()
    class Meta:
        ordering = ['-publish']  
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=250)
    body = models.TextField()
    email = models.EmailField(max_length=254)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active =models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"]),
        ]
    def __str__(self):
        return f"Comment by {self.name} on {self.post}"
    
    

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]



class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
    widget=forms.Textarea)

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag


def home(request, tag_slug=None):
    posts = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {'posts': posts, 'tag': tag}
    return render(request, 'home.html', context)


def post_detail_view(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    commments = post.comments.filter(active=True)
    form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    print(post_tags_ids)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    context = {
        "comments": commments,
        "form": form,
        "post": post,
        "similar_posts": similar_posts
    }
    return render(request, 'blog/details.html', context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'bdamilola00@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    context = {"post": post, "form": form, "sent": sent}
    return render(request, "blog/share.html", context)


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {"post": post, "comment": comment}
    return render(request, "blog/comment.html", context)


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_query=SearchQuery(query, config='spanish')
            search_vector=SearchVector('title', config='spanish', weight='A') + SearchVector('body', config='spanish', weight='B')
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
                ).filter(rank__gte=0.3).order_by('-rank')
    context = {"form": form, "query": query, "results": results}
    return render(request, "blog/search.html", context)

templates/_base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>eBlog</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}

</head>

<body class="bg-gray-900">
    {% comment %} LOAD NAVBAR HERE {% endcomment %}
    {% include 'includes/navbar.html' %}
    {% include "includes/sidebar.html" %}
    {% comment %} LOAD CONTENT HERE {% endcomment %}

    {% block content %}

    {% comment %} CONTENTS GOES HERE {% endcomment %}

    {% endblock  %}



    {% comment %} LOAD FOOTER HERE {% endcomment %}
    {% include 'includes/footer.html' %}
    

templates/blog/details.html
{% extends "_base.html" %}
{% block content %}
{% load blog_tags %}
<section class="bg-gray-900 text-white" style="height: calc(100vh - 70px)">
  <div class="max-w-screen-xl mx-auto">
    <div class="max-w-screen-xl mx-auto w-full space-y-4 py-10">
      <h1 class="text-4xl font-playfair text-center">
        {{ post.title|capfirst }}
      </h1>
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mx-auto mt-4 px-4 sm:px-0">
        <article
          class="block space-y-3 rounded-xl border border-gray-800 py-2 px-6 shadow-xl transition hover:border-blue-500/10 hover:shadow-blue-500/10"
        >
          <span class="inline-block rounded p-2 text-blue-500">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="size-10 text-blue-500"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path d="M12 14l9-5-9-5-9 5 9 5z" />
              <path
                d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z"
              />
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222"
              />
            </svg>
          </span>

          <h3 class="mt-0.5 text-lg font-medium text-white font-playfair">
            Published {{post.publish|date:"N d, Y "}} by
            {{post.author|capfirst}}
          </h3>

          <p class="mt-2 line-clamp-3 text-xs text-gray-300">
            {{post.body|markdown|linebreaks}}
          </p>
          <div class="flex justify-between items-center">
            <a
              href="{% url 'blog:home' %}"
              class="group mt-4 inline-flex items-center gap-1 text-sm font-medium text-blue-500"
            >
              Go home
              <span
                aria-hidden="true"
                class="block transition-all group-hover:ms-0.5 rtl:rotate-180"
              >
                &larr;
              </span>
            </a>

            <button
              class="bg-blue-500 hover:bg-blue-600 text-white rounded-md px-4 py-2"
            >
              <a
                class="text-sm font-medium"
                href="{% url 'blog:post_share' post.id %}"
              >
                Share post
              </a>
            </button>
          </div>
          {% with comments.count as total_comments %}
          <h2>{{ total_comments }} comment{{total_comments|pluralize}}</h2>
          {% endwith %}
        </article>

        <div>{% include "blog/includes/comment_form.html" %}</div>
      </div>

      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mx-auto mt-4 px-4 sm:px-0">
        {% comment %} COMMENT {% endcomment %}
        <div
          class="mt-2 border border-gray-800 shadow-xl max-w-sm mx-auto sm:mx-0 overflow-y-auto p-2 rounded-md"
          style="height: 150px; width: 400px"
        >
          {% for comment in comments %}
          <div class="mt-2 border border-gray-800 shadow-xl max-w-sm mx-auto sm:mx-0 p-2 rounded-md hover:bg-gray-800">
            <div class="flex items-center gap-x-2">
              <p class="text-white">{{ comment.name }}:</p>
              <span class="italic"> {{comment.body|linebreaks}} </span>
            </div>
            <span class="text-xs text-gray-300"> {{comment.created}} </span>
          </div>
          {% empty %}
          <p>There are no comments.</p>
          {% endfor %}
        </div>

        <div>
          <h2 class="text-sm font-bold text-white sm:text-xl">Similar Posts</h2>
          {% for post in similar_posts %}
          <div>
            <a
              href="{{post.get_absolute_url}}"
              class="mt-4 text-xs font-bold text-gray-300 whitespace-nowrap overflow-hidden text-ellipsis transition-all hover:text-blue-500"
            >
              {{ post.title }}
            </a>
            {% empty %}
            <p
              class="mt-1 font-bold text-gray-300 whitespace-nowrap overflow-hidden text-ellipsis text-sm"
            >
              No similar posts found
            </p>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/blog/includes/comment_form.html
<form method="post" action="{% url 'blog:post_comment' post.id %}" class="mb-0 mt-6 space-y-4 rounded-lg p-4 shadow-xl transition hover:border-blue-500/10 hover:shadow-blue-500/10 sm:p-6 lg:p-8">
  {% csrf_token %} 
  {% for field in form %}
  <div class="relative z-0 w-full mb-5 group">
    <label for={{ field.label }} class="sr-only">{{ field.label }}</label>
    <input  
    type="{{ field.field.widget.input_type }}"
    id="{{ field.id_for_label }}"
    name="{{ field.name }}"
    placeholder=" "
    required
    class="block py-2.5 px-0 w-full text-sm text-white bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"/>
    <label for={{ field.label }} class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">{{ field.label }}</label>
</div>
  {% endfor %}

  <button
    type="submit"
    value="Add comment"
    class="block w-full rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white"
  >
    Add Comment
  </button>
</form>

templates/blog/posts.html
{% load blog_tags %}
<div class="mt-8 grid grid-cols-1 gap-8 sm:grid-cols-2 md:grid-cols-3">
    {% for post in posts %}
    <div class="block space-y-3 rounded-xl border border-gray-800 p-6 shadow-xl transition hover:border-blue-500/10 hover:shadow-blue-500/10">
        <svg
            xmlns="http://www.w3.org/2000/svg"
            class="size-10 text-blue-500"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
        >
            <path d="M12 14l9-5-9-5-9 5 9 5z" />
            <path
            d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z"
            />
            <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222"
            />
        </svg>

        <h2
            class="mt-4 text-xl font-bold text-white whitespace-nowrap overflow-hidden text-ellipsis transition-all"
        >
            {{ post.title|capfirst }}
        </h2>

        <p class="mt-2 line-clamp-3 text-sm/relaxed text-gray-300">
            Published {{post.publish|date:"N d, Y "}} by {{post.author|capfirst}}
        </p>

      {{post.body|markdown|truncatewords_html:30}}

        <a href="{{post.get_absolute_url}}" class="group mt-4 inline-flex items-center gap-1 text-sm font-medium text-blue-500">
          Find out more

          <span
            aria-hidden="true"
            class="block transition-all group-hover:ms-0.5 rtl:rotate-180"
          >
            &rarr;
          </span>
        </a>
        <div class="flex justify-between items-center">
            <p class="mt-2 line-clamp-3 text-bold text-sm/relaxed text-gray-300">
            Tags
            </p>
        <div>
            {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="text-xs text-blue-500 no-underline hover:underline  hover:text-blue-600 hover:underline-offset-2 transition ease-in duration-300"
            >{{tag.name}}
            </a>
            {% if not forloop.last %}, {% endif %} {% endfor %}
        </div>
        </div>
    </div>
    {% endfor %}
</div>

templates/blog/search.html
{% extends "_base.html" %} 
{% load blog_tags %} 
{% block content %}

<div class="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8 lg:py-16">
  {% if query %}

  <div class="text-gray-300 space-y-2">
    <div class="text-center">
      <h2
        class="text-3xl font-bold sm:text-4xl font-playfair text-shadow text-white"
      >
        Post containing {{ query }}
      </h2>

      <p class="mt-4 font-poppins text-gray-300">
        {% with results.count as total_results %} Found {{total_results}}
        result{{total_results|pluralize}} 
        {% endwith %}
      </p>
    </div>

    <div class="mt-8 grid grid-cols-1 gap-8 sm:grid-cols-2 md:grid-cols-3">
      {% for post in results %}
      <div
        class="block space-y-3 rounded-xl border border-gray-800 p-6 shadow-xl transition hover:border-blue-500/10 hover:shadow-blue-500/10"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="size-10 text-blue-500"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path d="M12 14l9-5-9-5-9 5 9 5z" />
          <path
            d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z"
          />
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222"
          />
        </svg>

        <h2
          class="mt-4 text-xl font-bold text-white whitespace-nowrap overflow-hidden text-ellipsis transition-all"
        >
          {{ post.title|capfirst }}
        </h2>

        <p class="mt-2 line-clamp-3 text-sm/relaxed text-gray-300">
          Published {{post.publish|date:"N d, Y "}} by {{post.author|capfirst}}
        </p>

        {{post.body|markdown|truncatewords_html:30}}

        <a
          href="{{post.get_absolute_url}}"
          class="group mt-4 inline-flex items-center gap-1 text-sm font-medium text-blue-500"
        >
          Find out more

          <span
            aria-hidden="true"
            class="block transition-all group-hover:ms-0.5 rtl:rotate-180"
          >
            &rarr;
          </span>
        </a>
        <div class="flex justify-between items-center">
          <p class="mt-2 line-clamp-3 text-bold text-sm/relaxed text-gray-300">
            Tags
          </p>
          <div>
            {% for tag in post.tags.all %}
            <a
              href="{% url 'blog:post_list_by_tag' tag.slug %}"
              class="text-xs text-blue-500 no-underline hover:underline hover:text-blue-600 hover:underline-offset-2 transition ease-in duration-300"
              >{{tag.name}}
            </a>
            {% if not forloop.last %}, {% endif %} 
            {% endfor %}
          </div>
        </div>
      </div>
      {% empty %}
      <p>There are no results for your query.</p>
      {% endfor %}
    </div>
    <a href='{% url "blog:post_search" %}'> 
        <button class="block rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white mt-4">Search again</button>
    </a>
  </div>

  {% else %}
  <div class="space-y-4 max-w-lg mx-auto">
    <h1
      class="text-3xl font-bold sm:text-4xl font-playfair text-shadow text-white"
    >
      Search for posts
    </h1>
    <form method="get">
      {% for field in form %}
      <input
        type="{{ field.field.widget.input_type }}"
        id="{{ field.id_for_label }}"
        name="{{ field.name }}"
        placeholder="Search..."
        required
        class="block w-full p-2 ps-10 text-sm text-gray-600 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
      />
      {% endfor %}
      <button
        type="submit"
        value="search"
        class="block rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white mt-4"
      >
        Search
      </button>
    </form>
  </div>
  {% endif %}
</div>
{% endblock content %}

templates/blog/share.html
{% extends "_base.html" %} 
{% block content %}

<div class="mx-auto container px-4 py-16 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-lg">
    {% if sent %}
    <h1 class="text-center text-2xl font-bold text-indigo-600 sm:text-3xl">
      E-mail successfully sent
    </h1>

    <p class="mx-auto mt-4 max-w-md text-center text-gray-500">
      "{{post.title}}" was successfully sent to "{{form.cleaned_data.to}}".
    </p>

    {% else %}
    <h1 class="text-center text-2xl font-bold text-white sm:text-3xl font-playfair">
      Share <blockquote class="inline-block italic font-semibold">"{{post.title}}"</blockquote> by e-mail
    </h1>
    <form
      method="post"
      class="mb-0 mt-4 space-y-4 rounded-lg p-4 p-6 shadow-xl transition hover:border-blue-500/10 hover:shadow-blue-500/10 sm:p-6 lg:p-8"
    >      
      {% csrf_token %}
      {% for field in form %}
      <div class="relative z-0 w-full mb-5 group">
        <label for={{ field.label }} class="sr-only">{{ field.label }}</label>
        <input  
        type="{{ field.field.widget.input_type }}"
        id="{{ field.id_for_label }}"
        name="{{ field.name }}"
        placeholder=" "
        required
        class="block py-2.5 px-0 w-full text-sm text-gray-300 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"/>
        <label for={{ field.label }} class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">{{ field.label }}</label>
    </div>
      {% endfor %}
      <button
        type="submit"
        value="send e-mail"
        class="block w-full rounded-lg bg-indigo-600 px-5 py-3 text-sm font-medium text-white"
      >
        Send Email
      </button>

      <p class="text-center text-sm text-gray-400">
        More blogs?
        <a class="underline text-white" href='{% url "blog:home" %}'>Check here</a>
      </p>
    </form>
    {% endif %}
  </div>
</div>
{% endblock content %}

templates/includes/footer.html
{% load static %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>

</body>

</html>

templates/includes/navbar.html
{% load static %}
<header>
    <nav class="bg-gray-900 text-white shadow-2xl border-b border-pink-500/10 shadow-pink-900/10 box-shadow-0-4-4-0-pink-500/10 backdrop-blur-2xl sticky top-0 z-50">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{% url 'blog:home' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white text-shadow font-playfair">eBlog</span>
        </a>
        <div class="flex md:order-2">
            <button class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg  hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" type="button" data-drawer-target="drawer-navigation" data-drawer-show="drawer-navigation" aria-controls="drawer-navigation">
                <span class="sr-only">Open side bar</span>
                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                </svg>
            </button>
        </div>
        </div>
    </nav>
</header>

templates/includes/sidebar.html
{% load blog_tags %}
 <div id="drawer-navigation" class="fixed top-16 left-0 z-40 w-72 h-screen p-4 overflow-y-auto transition-transform -translate-x-full bg-gray-800" tabindex="-1" aria-labelledby="drawer-navigation-label">
     <button type="button" data-drawer-hide="drawer-navigation" aria-controls="drawer-navigation" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 absolute top-2.5 end-2.5 inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" >
         <svg aria-hidden="true" class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
         <span class="sr-only">Close menu</span>
     </button>
   <div class="py-4 overflow-y-auto space-y-2">
    <div>
        <h5 class="text-base font-semibold text-white text-sm mb-1">Latest Posts</h5>
      {% show_latest_posts 3 %}
    </div>

    <div>
        <h5 class="text-base font-semibold text-white text-sm mb-1">Popular Posts</h5>
        {% get_most_commented_posts as most_commented_posts %}
        <ul class="space-y-1">
            {% for post in most_commented_posts  %}
            <li class="text-xs text-gray-300 hover:text-blue-500 hover:underline hover:underline-offset-2 transition duration-250 ms-4">
                <a href="{{ post.get_absolute_url }}">{{post.title | capfirst}}</a>
            </li>
            {% endfor %}
        </ul>

        <h3 class="text-base font-semibold text-white text-xl font-playfair mt-8"><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></h3>
    </div>
    </div>
 </div>
 